export enum SystemPermission {
  USER_VIEW = 'system.user.view',
  USER_CREATE = 'system.user.create',
  USER_UPDATE = 'system.user.update',
  USER_DELETE = 'system.user.delete',
  USER_PERMISSION_MANAGE = 'system.user.permission.manage',
  ROLE_VIEW = 'system.role.view',
  ROLE_CREATE = 'system.role.create',
  ROLE_UPDATE = 'system.role.update',
  ROLE_DELETE = 'system.role.delete',
  ROLE_PERMISSION_MANAGE = 'system.role.permission.manage',
  PRODUCTION_DEPARTMENT_VIEW = 'production.department.view',
  PRODUCTION_DEPARTMENT_CREATE = 'production.department.create',
  PRODUCTION_DEPARTMENT_UPDATE = 'production.department.update',
  PRODUCTION_DEPARTMENT_DELETE = 'production.department.delete',
  PRODUCTION_YARD_VIEW = 'production.yard.view',
  PRODUCTION_YARD_CREATE = 'production.yard.create',
  PRODUCTION_YARD_UPDATE = 'production.yard.update',
  PRODUCTION_YARD_DELETE = 'production.yard.delete',
  PRODUCTION_ASSIGNMENT_VIEW = 'production.assignment.view',
  PRODUCTION_ASSIGNMENT_MANAGE = 'production.assignment.manage',
  INVENTORY_CATEGORY_VIEW = 'inventory.category.view',
  INVENTORY_CATEGORY_CREATE = 'inventory.category.create',
  INVENTORY_CATEGORY_UPDATE = 'inventory.category.update',
  INVENTORY_CATEGORY_DELETE = 'inventory.category.delete',
  INVENTORY_PRODUCT_VIEW = 'inventory.product.view',
  INVENTORY_PRODUCT_CREATE = 'inventory.product.create',
  INVENTORY_PRODUCT_UPDATE = 'inventory.product.update',
  INVENTORY_PRODUCT_DELETE = 'inventory.product.delete',
}


